### PR TITLE
Validate ai configuration while update

### LINKED ISSUE #1080: Updating function app success when speicfy <disableAppInsights> and <appInsightsKey> at the same time
### Plugin name and version
azure-functions-maven-plugin 1.4.2-SNAPSHOT
### Plugin configuration in your `pom.xml`
```
 <configuration>
 <appName>${functionAppName}</appName>
 <resourceGroup>harrytest04</resourceGroup>
 <appServicePlanName>harrytest04-app-service-plan</appServicePlanName>
 <region>westus</region>
 <runtime>
 <os>windows</os>
 </runtime>
 <appInsightsInstance>harryai12</appInsightsInstance>
 <disableAppInsights>true</disableAppInsights>
 <appSettings>
 <property>
 <name>FUNCTIONS_EXTENSION_VERSION</name>
 <value>~3</value>
 </property>
 <property>
 <name>test</name>
 <value>12</value>
 </property>
 </appSettings>
 </configuration>
```

### Actual behavior
If user speicfy `<disableAppInsights>` and `<appInsightsKey>` or `<appInsightsInstance>` at the same time, the plugin will not throw an exception when update function app. what's more, it can update appsettings and remove the APPINSIGHTS_INSTRUMENTATIONKEY in app settings.

image

### PR DESCRIPTION
**Pull request by Flanker32**
Validate ai configuration while update, fixes #1080

### CODE REVIEW

File: azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/DeployMojo.java [hunk 1]
```diff
@@ -155,6 +155,7 @@ protected void updateFunctionApp(final FunctionApp app) throws AzureAuthFailureE
         if (isDisableAppInsights()) {
```
Comment (andxu) [inline azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/DeployMojo.java:155]: Move validateApplicationInsightsConfiguration to line above  ```if (isDisableAppInsights()) {```
