### PR TITLE
Fix possible NPE for `TailingDebouncer`

### LINKED ISSUE #6120: [IntelliJ][ReportedByUser] AzureOperationException: list all function modules in project
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.58.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for ActionGroup(com.intellij.execution.actions.RunContextAction, id=RunClass) with text=Run context configuration, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: list all function modules in project(backoffice)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.function.runner.core.FunctionUtils.listFunctionModules(FunctionUtils.java:140)
	at com.microsoft.azure.toolkit.intellij.function.runner.core.FunctionUtils.getFunctionModuleByName(FunctionUtils.java:152)
	at com.microsoft.azure.toolkit.intellij.function.runner.localrun.FunctionRunConfiguration.getMo

### PR DESCRIPTION
**Pull request by Flanker32**
Fix possible NPE for `TailingDebouncer`, fixes https://github.com/microsoft/azure-tools-for-java/issues/6120

### CODE REVIEW

File: azure-toolkit-libs/azure-toolkit-common-lib/src/main/java/com/microsoft/azure/toolkit/lib/common/utils/TailingDebouncer.java [hunk 1]
```diff
@@ -30,8 +30,10 @@ public synchronized void debounce() {
         this.timer = Observable.timer(this.delay, TimeUnit.MILLISECONDS)
             .subscribeOn(Schedulers.io())
             .subscribe(ignore -> {
-                this.debounced.run();
-                this.timer = null;
+                synchronized (TailingDebouncer.this) {
+                    this.debounced.run();
```
Comment (wangmingliang-ms) [inline azure-toolkit-libs/azure-toolkit-common-lib/src/main/java/com/microsoft/azure/toolkit/lib/common/utils/TailingDebouncer.java:34]: this line should be moved out of the `synchronized` block

Comment (wangmingliang-ms) [inline azure-toolkit-libs/azure-toolkit-common-lib/src/main/java/com/microsoft/azure/toolkit/lib/common/utils/TailingDebouncer.java:33]: this line should be moved out of the `synchronized` block, 
it would, otherwise, make the debounced func run sequentially.

**Review by wangmingliang-ms — APPROVED** [review]
