### PR TITLE
Use MSI to authenticate in Cloud Shell

### LINKED ISSUE #382: mvn azure-webapp:deploy does not work in CloudShell
### Plugin name and version
mvn azure-webapp:deploy
version 1.4.0

### Plugin configuration in your `pom.xml`

```XML
<plugins> 
	...

    <plugin>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-webapp-maven-plugin</artifactId>
        <version>1.4.0</version>
        <configuration>
            <resourceGroup>${RESOURCEGROUP_NAME}</resourceGroup>
            <appName>${WEBAPP_NAME}</appName>
            <linuxRuntime>tomcat 8.5-jre8</linuxRuntime>
        </configuration>
    </plugin>
    …

</plugins>
```

### Expected behavior
The war should deploy to the App Service

### Actual behavior
Error says it can't authenticate with the Azure CLI. But I'm logged into the CLI and using CloudShell while logged into the Azure portal. I tried executing the maven command with and without having an access token within `/home/jason/.azure/accessTokens.json`.

# Attempt without Access Tokens:
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-1022-azure", arch: "amd64", family: "unix"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/jason/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/share/maven/conf/toolchains.xml
[DEBUG] Reading user toolchains from /home/jason/.m2/toolchains.xml
[DEBUG] Using local repository at /home/jason/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/jason/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project org.springframework.samples:spring-petclinic:war:5.0.8: (none)
[DEBUG] Looking up lifecyle mappings for packaging war from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix azure-webapp from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix azure-webapp to com.microsoft.azure:azure-webapp-maven-plugin from POM org.springframework.samples:spring-petclinic:war:5.0.8
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: org.springframework.samples:spring-petclinic:war:5.0.8
[DEBUG] Tasks:   [azure-webapp:deploy]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building petclinic 5.0.8
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix azure-webapp from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix azure-webapp to com.microsoft.azure:azure-webapp-maven-plugin from POM org.springframework.samples:spring-petclinic:war:5.0.8
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       org.springframework.samples:spring-petclinic:5.0.8
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] Repositories (dependencies): [repository.spring.milestone (http://repo.spring.io/milestone, default, releases+snapshots), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <allowTelemetry default-value="true">${allowTelemetry}</allowTelemetry>
  <appName>freebergpetclinic</appName>
  <appServicePlanName>${appServicePlanName}</appServicePlanName>
  <appServicePlanResourceGroup>${appServicePlanResourceGroup}</appServicePlanResourceGroup>
  <buildDirectory default-value="${project.build.directory}"/>
  <deploymentType>${deploymentType}</deploymentType>
  <failsOnError default-value="true">${failsOnError}</failsOnError>
  <jarFile>${webapp.jarFile}</jarFile>
  <javaVersion>${webapp.javaVersion}</javaVersion>
  <javaWebContainer default-value="tomcat 8.5">${webapp.javaWebContainer}</javaWebContainer>
  <linuxRuntime>tomcat 8.5-jre8</linuxRuntime>
  <path default-value="/">${webapp.path}</path>
  <plugin default-value="${plugin}"/>
  <pricingTier default-value="S1">${webapp.pricingTier}</pricingTier>
  <project default-value="${project}"/>
  <region default-value="westus">${region}</region>
  <resourceGroup>freebergDemo</resourceGroup>
  <session default-value="${session}"/>
  <settings default-value="${settings}"/>
  <skip default-value="false">${webapp.skip}</skip>
  <stopAppDuringDeployment default-value="false">${webapp.stopAppDuringDeployment}</stopAppDuringDeployment>
  <warFile>${webapp.warFile}</warFile>
</configuration>
[DEBUG] =======================================================================
[INFO]
[INFO] --- azure-webapp-maven-plugin:1.4.0:deploy (default-cli) @ spring-petclinic ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=6, ConflictMarker.markTime=1, ConflictMarker.nodeCount=350, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=111, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=19, ConflictResolver.conflictItemCount=256, DefaultDependencyCollector.collectTime=527, DefaultDependencyCollector.transformTime=29}
[DEBUG] com.microsoft.azure:azure-webapp-maven-plugin:jar:1.4.0:
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:3.3.3:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0:compile
[DEBUG]    org.apache.maven:maven-core:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.3.3:compile
[DEBUG]          org.apache.maven:maven-builder-support:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.3.3:compile
[DEBUG]          org.eclipse.aether:aether-spi:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-impl:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-api:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-util:jar:1.0.2.v20150114:compile
[DEBUG]       org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5:compile
[DEBUG]          javax.inject:javax.inject:jar:1:compile
[DEBUG]          aopalliance:aopalliance:jar:1.0:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]    org.apache.maven:maven-settings:jar:3.3.3:compile
[DEBUG]    org.apache.maven:maven-model:jar:3.3.3:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.0.20:compile
[DEBUG]    com.microsoft.azure:azure-maven-plugin-lib:jar:1.1.1:compile
[DEBUG]       org.apache.maven.shared:maven-filtering:jar:3.0.0:compile
[DEBUG]          org.apache.maven.shared:maven-shared-utils:jar:3.0.0:compile
[DEBUG]             com.google.code.findbugs:jsr305:jar:2.0.1:compile
[DEBUG]          org.sonatype.plexus:plexus-build-api:jar:0.0.7:compile
[DEBUG]       com.microsoft.azure:azure:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-client-runtime:jar:1.6.0:compile
[DEBUG]             com.microsoft.rest:client-runtime:jar:1.6.0:compile
[DEBUG]                com.google.guava:guava:jar:20.0:compile
[DEBUG]                com.squareup.retrofit2:retrofit:jar:2.4.0:compile
[DEBUG]                com.squareup.okhttp3:okhttp:jar:3.11.0:compile
[DEBUG]                   com.squareup.okio:okio:jar:1.14.0:compile
[DEBUG]                com.squareup.okhttp3:logging-interceptor:jar:3.11.0:compile
[DEBUG]                com.squareup.okhttp3:okhttp-urlconnection:jar:3.11.0:compile
[DEBUG]                com.squareup.retrofit2:converter-jackson:jar:2.4.0:compile
[DEBUG]                   com.fasterxml.jackson.core:jackson-databind:jar:2.9.4:compile
[DEBUG]                com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.4:compile
[DEBUG]                   com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[DEBUG]                com.squareup.retrofit2:adapter-rxjava:jar:2.4.0:compile
[DEBUG]          com.microsoft.azure:azure-client-authentication:jar:1.6.0:compile
[DEBUG]             com.microsoft.azure:adal4j:jar:1.1.2:compile
[DEBUG]                com.nimbusds:oauth2-oidc-sdk:jar:4.5:compile
[DEBUG]                   javax.mail:mail:jar:1.4.7:compile
[DEBUG]                      javax.activation:activation:jar:1.1:compile
[DEBUG]                   net.jcip:jcip-annotations:jar:1.0:compile
[DEBUG]                   net.minidev:json-smart:jar:1.1.1:compile
[DEBUG]                   com.nimbusds:lang-tag:jar:1.4:compile
[DEBUG]                   com.nimbusds:nimbus-jose-jwt:jar:3.1.2:compile
[DEBUG]                      org.bouncycastle:bcprov-jdk15on:jar:1.51:compile
[DEBUG]             com.microsoft.azure:azure-annotations:jar:1.2.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-resources:jar:1.14.0:compile
[DEBUG]             org.slf4j:slf4j-simple:jar:1.7.5:compile
[DEBUG]             io.reactivex:rxjava:jar:1.3.8:compile
[DEBUG]             org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-storage:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-network:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-compute:jar:1.14.0:compile
[DEBUG]             com.google.code.gson:gson:jar:2.2.4:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-graph-rbac:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-keyvault:jar:1.14.0:compile
[DEBUG]             com.microsoft.azure:azure-keyvault:jar:1.0.0:compile
[DEBUG]                com.microsoft.azure:azure-keyvault-webkey:jar:1.0.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-batch:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-trafficmanager:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-dns:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-redis:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-appservice:jar:1.14.0:compile
[DEBUG]             com.microsoft.azure:azure-storage:jar:6.1.0:compile
[DEBUG]                com.microsoft.azure:azure-keyvault-core:jar:0.8.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-locks:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-eventhub:jar:1.14.0:compile
[DEBUG]             com.fasterxml.jackson.core:jackson-core:jar:2.9.4:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-cdn:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-sql:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-containerinstance:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-containerregistry:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-containerservice:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-cosmosdb:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-search:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-msi:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-monitor:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-servicebus:jar:1.14.0:compile
[DEBUG]             joda-time:joda-time:jar:2.1:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-batchai:jar:1.14.0:compile
[DEBUG]       com.microsoft.azure:applicationinsights-core:jar:1.0.9:compile
[DEBUG]          eu.infomas:annotation-detector:jar:3.0.4:compile
[DEBUG]          commons-io:commons-io:jar:2.4:compile
[DEBUG]          org.apache.commons:commons-lang3:jar:3.1:compile
[DEBUG]          org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[DEBUG]             commons-logging:commons-logging:jar:1.2:compile
[DEBUG]             commons-codec:commons-codec:jar:1.9:compile
[DEBUG]       commons-net:commons-net:jar:3.6:compile
[DEBUG]       org.zeroturnaround:zt-zip:jar:1.13:compile
[DEBUG]          org.slf4j:slf4j-api:jar:1.6.6:compile
[DEBUG]    junit:junit:jar:4.12:compile
[DEBUG]       org.hamcrest:hamcrest-core:jar:1.3:compile
[DEBUG] Created new class realm plugin>com.microsoft.azure:azure-webapp-maven-plugin:1.4.0
[DEBUG] Importing foreign packages into class realm plugin>com.microsoft.azure:azure-webapp-maven-plugin:1.4.0
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>com.microsoft.azure:azure-webapp-maven-plugin:1.4.0
[DEBUG]   Included: com.microsoft.azure:azure-webapp-maven-plugin:jar:1.4.0
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: javax.annotation:jsr250-api:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0
[DEBUG]   Included: org.apache.maven:maven-builder-support:jar:3.3.3
[DEBUG]   Included: org.eclipse.aether:aether-util:jar:1.0.2.v20150114
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.21
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.20
[DEBUG]   Included: com.microsoft.azure:azure-maven-plugin-lib:jar:1.1.1
[DEBUG]   Included: org.apache.maven.shared:maven-filtering:jar:3.0.0
[DEBUG]   Included: org.apache.maven.shared:maven-shared-utils:jar:3.0.0
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:2.0.1
[DEBUG]   Included: org.sonatype.plexus:plexus-build-api:jar:0.0.7
[DEBUG]   Included: com.microsoft.azure:azure:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-client-runtime:jar:1.6.0
[DEBUG]   Included: com.microsoft.rest:client-runtime:jar:1.6.0
[DEBUG]   Included: com.google.guava:guava:jar:20.0
[DEBUG]   Included: com.squareup.retrofit2:retrofit:jar:2.4.0
[DEBUG]   Included: com.squareup.okhttp3:okhttp:jar:3.11.0
[DEBUG]   Included: com.squareup.okio:okio:jar:1.14.0
[DEBUG]   Included: com.squareup.okhttp3:logging-interceptor:jar:3.11.0
[DEBUG]   Included: com.squareup.okhttp3:okhttp-urlconnection:jar:3.11.0
[DEBUG]   Included: com.squareup.retrofit2:converter-jackson:jar:2.4.0
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-databind:jar:2.9.4
[DEBUG]   Included: com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.4
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0
[DEBUG]   Included: com.squareup.retrofit2:adapter-rxjava:jar:2.4.0
[DEBUG]   Included: com.microsoft.azure:azure-client-authentication:jar:1.6.0
[DEBUG]   Included: com.microsoft.azure:adal4j:jar:1.1.2
[DEBUG]   Included: com.nimbusds:oauth2-oidc-sdk:jar:4.5
[DEBUG]   Included: javax.mail:mail:jar:1.4.7
[DEBUG]   Included: javax.activation:activation:jar:1.1
[DEBUG]   Included: net.jcip:jcip-annotations:jar:1.0
[DEBUG]   Included: net.minidev:json-smart:jar:1.1.1
[DEBUG]   Included: com.nimbusds:lang-tag:jar:1.4
[DEBUG]   Included: com.nimbusds:nimbus-jose-jwt:jar:3.1.2
[DEBUG]   Included: org.bouncycastle:bcprov-jdk15on:jar:1.51
[DEBUG]   Included: com.microsoft.azure:azure-annotations:jar:1.2.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-resources:jar:1.14.0
[DEBUG]   Included: org.slf4j:slf4j-simple:jar:1.7.5
[DEBUG]   Included: io.reactivex:rxjava:jar:1.3.8
[DEBUG]   Included: org.apache.httpcomponents:httpcore:jar:4.4.5
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-storage:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-network:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-compute:jar:1.14.0
[DEBUG]   Included: com.google.code.gson:gson:jar:2.2.4
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-graph-rbac:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-keyvault:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-keyvault:jar:1.0.0
[DEBUG]   Included: com.microsoft.azure:azure-keyvault-webkey:jar:1.0.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-batch:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-trafficmanager:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-dns:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-redis:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-appservice:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-storage:jar:6.1.0
[DEBUG]   Included: com.microsoft.azure:azure-keyvault-core:jar:0.8.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-locks:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-eventhub:jar:1.14.0
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-core:jar:2.9.4
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-cdn:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-sql:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-containerinstance:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-containerregistry:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-containerservice:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-cosmosdb:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-search:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-msi:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-monitor:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-servicebus:jar:1.14.0
[DEBUG]   Included: joda-time:joda-time:jar:2.1
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-batchai:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:applicationinsights-core:jar:1.0.9
[DEBUG]   Included: eu.infomas:annotation-detector:jar:3.0.4
[DEBUG]   Included: commons-io:commons-io:jar:2.4
[DEBUG]   Included: org.apache.commons:commons-lang3:jar:3.1
[DEBUG]   Included: org.apache.httpcomponents:httpclient:jar:4.5.3
[DEBUG]   Included: commons-logging:commons-logging:jar:1.2
[DEBUG]   Included: commons-codec:commons-codec:jar:1.9
[DEBUG]   Included: commons-net:commons-net:jar:3.6
[DEBUG]   Included: org.zeroturnaround:zt-zip:jar:1.13
[DEBUG]   Included: junit:junit:jar:4.12
[DEBUG]   Included: org.hamcrest:hamcrest-core:jar:1.3
[DEBUG] Configuring mojo com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy from plugin realm ClassRealm[plugin>com.microsoft.azure:azure-webapp-maven-plugin:1.4.0, parent: sun.misc.Launcher$AppClassLoader@1b6d3586]
[DEBUG] Configuring mojo 'com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy' with basic configurator -->
[DEBUG]   (f) allowTelemetry = true
[DEBUG]   (f) appName = freebergpetclinic
[DEBUG]   (f) buildDirectory = /usr/jason/clouddrive/e2e-java-experience-in-app-service-linux/initial-cloudshell/spring-framework-petclinic/target
[DEBUG]   (f) failsOnError = true
[DEBUG]   (f) javaWebContainer = tomcat 8.5
[DEBUG]   (f) linuxRuntime = tomcat 8.5-jre8
[DEBUG]   (f) path = /
[DEBUG]   (f) plugin = Component Descriptor: role: 'org.apache.maven.plugin.Mojo', implementation: 'com.microsoft.azure.maven.webapp.DeployMojo', role hint: 'com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy'
role: 'org.apache.maven.plugin.Mojo', implementation: 'com.microsoft.azure.maven.webapp.HelpMojo', role hint: 'com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:help'
---
[DEBUG]   (f) pricingTier = S1
[DEBUG]   (f) project = MavenProject: org.springframework.samples:spring-petclinic:5.0.8 @ /usr/jason/clouddrive/e2e-java-experience-in-app-service-linux/initial-cloudshell/spring-framework-petclinic/pom.xml
[DEBUG]   (f) region = westus
[DEBUG]   (f) resourceGroup = freebergDemo
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@29f0802c
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@60f2e0bd
[DEBUG]   (f) skip = false
[DEBUG]   (f) stopAppDuringDeployment = false
[DEBUG] -- end configuration --
AI: INFO 05-09-2018 19:38, 1: Configuration file has been successfully found as resource
AI: INFO 05-09-2018 19:38, 1: Configuration file has been successfully found as resource
Cannot read files /home/jason/.azure/azureProfile.json and /home/jason/.azure/accessTokens.json. Are you logged in Azure CLI?
[DEBUG] Failed to authenticate with Azure CLI 2.0
[DEBUG]
java.io.FileNotFoundException: /home/jason/.azure/accessTokens.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:766)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2909)
        at com.microsoft.azure.credentials.AzureCliCredentials.loadAccessTokens(AzureCliCredentials.java:45)
        at com.microsoft.azure.credentials.AzureCliCredentials.create(AzureCliCredentials.java:95)
        at com.microsoft.azure.credentials.AzureCliCredentials.create(AzureCliCredentials.java:78)
        at com.microsoft.azure.maven.auth.AzureAuthHelper.getAuthObjFromAzureCli(AzureAuthHelper.java:203)
        at com.microsoft.azure.maven.auth.AzureAuthHelper.getAuthObj(AzureAuthHelper.java:129)
        at com.microsoft.azure.maven.auth.AzureAuthHelper.getAzureClient(AzureAuthHelper.java:71)
        at com.microsoft.azure.maven.AbstractAzureMojo.getAzureClient(AbstractAzureMojo.java:205)
        at com.microsoft.azure.maven.webapp.AbstractWebAppMojo.getWebApp(AbstractWebAppMojo.java:264)
        at com.microsoft.azure.maven.webapp.DeployMojo.createOrUpdateWebApp(DeployMojo.java:52)
        at com.microsoft.azure.maven.webapp.DeployMojo.doExecute(DeployMojo.java:47)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:288)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.163 s
[INFO] Finished at: 2018-09-05T19:38:30+00:00
[INFO] Final Memory: 60M/251M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project spring-petclinic: Failed to authenticate with Azure. Please check your configuration. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project spring-petclinic: Failed to authenticate with Azure. Please check your configuration.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to authenticate with Azure. Please check your configuration.
        at com.microsoft.azure.maven.AbstractAzureMojo.handleException(AbstractAzureMojo.java:347)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:293)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.microsoft.azure.maven.auth.AzureAuthFailureException: Failed to authenticate with Azure. Please check your configuration.
        at com.microsoft.azure.maven.AbstractAzureMojo.getAzureClient(AbstractAzureMojo.java:208)
        at com.microsoft.azure.maven.webapp.AbstractWebAppMojo.getWebApp(AbstractWebAppMojo.java:264)
        at com.microsoft.azure.maven.webapp.DeployMojo.createOrUpdateWebApp(DeployMojo.java:52)
        at com.microsoft.azure.maven.webapp.DeployMojo.doExecute(DeployMojo.java:47)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:288)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

# Attempt **with** access tokens:

```bash
Apache Maven 3.3.9Maven home: /usr/share/mavenJava version: 1.8.0_181, vendor: Oracle CorporationJava home: /usr/lib/jvm/java-8-openjdk-amd64/jreDefault locale: en_US, platform encoding: UTF-8OS name: "linux", version: "4.15.0-1022-azure", arch: "amd64", family: "unix"[DEBUG] Created new class realm maven.api[DEBUG] Importing foreign packages into class realm maven.api[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/jason/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/share/maven/conf/toolchains.xml
[DEBUG] Reading user toolchains from /home/jason/.m2/toolchains.xml
[DEBUG] Using local repository at /home/jason/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/jason/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project org.springframework.samples:spring-petclinic:war:5.0.8: (none)
[DEBUG] Looking up lifecyle mappings for packaging war from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix azure-webapp from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix azure-webapp to com.microsoft.azure:azure-webapp-maven-plugin from POM org.springframework.samples:spring-petclinic:war:5.0.8
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: org.springframework.samples:spring-petclinic:war:5.0.8
[DEBUG] Tasks:   [azure-webapp:deploy]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building petclinic 5.0.8
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix azure-webapp from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix azure-webapp to com.microsoft.azure:azure-webapp-maven-plugin from POM org.springframework.samples:spring-petclinic:war:5.0.8
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       org.springframework.samples:spring-petclinic:5.0.8
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] Repositories (dependencies): [repository.spring.milestone (http://repo.spring.io/milestone, default, releases+snapshots), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <allowTelemetry default-value="true">${allowTelemetry}</allowTelemetry>
  <appName>freebergpetclinic</appName>
  <appServicePlanName>${appServicePlanName}</appServicePlanName>
  <appServicePlanResourceGroup>${appServicePlanResourceGroup}</appServicePlanResourceGroup>
  <buildDirectory default-value="${project.build.directory}"/>
  <deploymentType>${deploymentType}</deploymentType>
  <failsOnError default-value="true">${failsOnError}</failsOnError>
  <jarFile>${webapp.jarFile}</jarFile>
  <javaVersion>${webapp.javaVersion}</javaVersion>
  <javaWebContainer default-value="tomcat 8.5">${webapp.javaWebContainer}</javaWebContainer>
  <linuxRuntime>tomcat 8.5-jre8</linuxRuntime>
  <path default-value="/">${webapp.path}</path>
  <plugin default-value="${plugin}"/>
  <pricingTier default-value="S1">${webapp.pricingTier}</pricingTier>
  <project default-value="${project}"/>
  <region default-value="westus">${region}</region>
  <resourceGroup>freebergDemo</resourceGroup>
  <session default-value="${session}"/>
  <settings default-value="${settings}"/>
  <skip default-value="false">${webapp.skip}</skip>
  <stopAppDuringDeployment default-value="false">${webapp.stopAppDuringDeployment}</stopAppDuringDeployment>
  <warFile>${webapp.warFile}</warFile>
</configuration>
[DEBUG] =======================================================================
[INFO]
[INFO] --- azure-webapp-maven-plugin:1.4.0:deploy (default-cli) @ spring-petclinic ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=2, ConflictMarker.markTime=1, ConflictMarker.nodeCount=350, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=111, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=13, ConflictResolver.conflictItemCount=256, DefaultDependencyCollector.collectTime=521, DefaultDependencyCollector.transformTime=19}
[DEBUG] com.microsoft.azure:azure-webapp-maven-plugin:jar:1.4.0:
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:3.3.3:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0:compile
[DEBUG]    org.apache.maven:maven-core:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.3.3:compile
[DEBUG]          org.apache.maven:maven-builder-support:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.3.3:compile
[DEBUG]          org.eclipse.aether:aether-spi:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-impl:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-api:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-util:jar:1.0.2.v20150114:compile
[DEBUG]       org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5:compile
[DEBUG]          javax.inject:javax.inject:jar:1:compile
[DEBUG]          aopalliance:aopalliance:jar:1.0:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]    org.apache.maven:maven-settings:jar:3.3.3:compile
[DEBUG]    org.apache.maven:maven-model:jar:3.3.3:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.0.20:compile
[DEBUG]    com.microsoft.azure:azure-maven-plugin-lib:jar:1.1.1:compile
[DEBUG]       org.apache.maven.shared:maven-filtering:jar:3.0.0:compile
[DEBUG]          org.apache.maven.shared:maven-shared-utils:jar:3.0.0:compile
[DEBUG]             com.google.code.findbugs:jsr305:jar:2.0.1:compile
[DEBUG]          org.sonatype.plexus:plexus-build-api:jar:0.0.7:compile
[DEBUG]       com.microsoft.azure:azure:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-client-runtime:jar:1.6.0:compile
[DEBUG]             com.microsoft.rest:client-runtime:jar:1.6.0:compile
[DEBUG]                com.google.guava:guava:jar:20.0:compile
[DEBUG]                com.squareup.retrofit2:retrofit:jar:2.4.0:compile
[DEBUG]                com.squareup.okhttp3:okhttp:jar:3.11.0:compile
[DEBUG]                   com.squareup.okio:okio:jar:1.14.0:compile
[DEBUG]                com.squareup.okhttp3:logging-interceptor:jar:3.11.0:compile
[DEBUG]                com.squareup.okhttp3:okhttp-urlconnection:jar:3.11.0:compile
[DEBUG]                com.squareup.retrofit2:converter-jackson:jar:2.4.0:compile
[DEBUG]                   com.fasterxml.jackson.core:jackson-databind:jar:2.9.4:compile
[DEBUG]                com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.4:compile
[DEBUG]                   com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[DEBUG]                com.squareup.retrofit2:adapter-rxjava:jar:2.4.0:compile
[DEBUG]          com.microsoft.azure:azure-client-authentication:jar:1.6.0:compile
[DEBUG]             com.microsoft.azure:adal4j:jar:1.1.2:compile
[DEBUG]                com.nimbusds:oauth2-oidc-sdk:jar:4.5:compile
[DEBUG]                   javax.mail:mail:jar:1.4.7:compile
[DEBUG]                      javax.activation:activation:jar:1.1:compile
[DEBUG]                   net.jcip:jcip-annotations:jar:1.0:compile
[DEBUG]                   net.minidev:json-smart:jar:1.1.1:compile
[DEBUG]                   com.nimbusds:lang-tag:jar:1.4:compile
[DEBUG]                   com.nimbusds:nimbus-jose-jwt:jar:3.1.2:compile
[DEBUG]                      org.bouncycastle:bcprov-jdk15on:jar:1.51:compile
[DEBUG]             com.microsoft.azure:azure-annotations:jar:1.2.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-resources:jar:1.14.0:compile
[DEBUG]             org.slf4j:slf4j-simple:jar:1.7.5:compile
[DEBUG]             io.reactivex:rxjava:jar:1.3.8:compile
[DEBUG]             org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-storage:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-network:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-compute:jar:1.14.0:compile
[DEBUG]             com.google.code.gson:gson:jar:2.2.4:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-graph-rbac:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-keyvault:jar:1.14.0:compile
[DEBUG]             com.microsoft.azure:azure-keyvault:jar:1.0.0:compile
[DEBUG]                com.microsoft.azure:azure-keyvault-webkey:jar:1.0.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-batch:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-trafficmanager:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-dns:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-redis:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-appservice:jar:1.14.0:compile
[DEBUG]             com.microsoft.azure:azure-storage:jar:6.1.0:compile
[DEBUG]                com.microsoft.azure:azure-keyvault-core:jar:0.8.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-locks:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-eventhub:jar:1.14.0:compile
[DEBUG]             com.fasterxml.jackson.core:jackson-core:jar:2.9.4:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-cdn:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-sql:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-containerinstance:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-containerregistry:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-containerservice:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-cosmosdb:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-search:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-msi:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-monitor:jar:1.14.0:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-servicebus:jar:1.14.0:compile
[DEBUG]             joda-time:joda-time:jar:2.1:compile
[DEBUG]          com.microsoft.azure:azure-mgmt-batchai:jar:1.14.0:compile
[DEBUG]       com.microsoft.azure:applicationinsights-core:jar:1.0.9:compile
[DEBUG]          eu.infomas:annotation-detector:jar:3.0.4:compile
[DEBUG]          commons-io:commons-io:jar:2.4:compile
[DEBUG]          org.apache.commons:commons-lang3:jar:3.1:compile
[DEBUG]          org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[DEBUG]             commons-logging:commons-logging:jar:1.2:compile
[DEBUG]             commons-codec:commons-codec:jar:1.9:compile
[DEBUG]       commons-net:commons-net:jar:3.6:compile
[DEBUG]       org.zeroturnaround:zt-zip:jar:1.13:compile
[DEBUG]          org.slf4j:slf4j-api:jar:1.6.6:compile
[DEBUG]    junit:junit:jar:4.12:compile
[DEBUG]       org.hamcrest:hamcrest-core:jar:1.3:compile
[DEBUG] Created new class realm plugin>com.microsoft.azure:azure-webapp-maven-plugin:1.4.0
[DEBUG] Importing foreign packages into class realm plugin>com.microsoft.azure:azure-webapp-maven-plugin:1.4.0
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>com.microsoft.azure:azure-webapp-maven-plugin:1.4.0
[DEBUG]   Included: com.microsoft.azure:azure-webapp-maven-plugin:jar:1.4.0
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: javax.annotation:jsr250-api:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0
[DEBUG]   Included: org.apache.maven:maven-builder-support:jar:3.3.3
[DEBUG]   Included: org.eclipse.aether:aether-util:jar:1.0.2.v20150114
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.21
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.20
[DEBUG]   Included: com.microsoft.azure:azure-maven-plugin-lib:jar:1.1.1
[DEBUG]   Included: org.apache.maven.shared:maven-filtering:jar:3.0.0
[DEBUG]   Included: org.apache.maven.shared:maven-shared-utils:jar:3.0.0
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:2.0.1
[DEBUG]   Included: org.sonatype.plexus:plexus-build-api:jar:0.0.7
[DEBUG]   Included: com.microsoft.azure:azure:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-client-runtime:jar:1.6.0
[DEBUG]   Included: com.microsoft.rest:client-runtime:jar:1.6.0
[DEBUG]   Included: com.google.guava:guava:jar:20.0
[DEBUG]   Included: com.squareup.retrofit2:retrofit:jar:2.4.0
[DEBUG]   Included: com.squareup.okhttp3:okhttp:jar:3.11.0
[DEBUG]   Included: com.squareup.okio:okio:jar:1.14.0
[DEBUG]   Included: com.squareup.okhttp3:logging-interceptor:jar:3.11.0
[DEBUG]   Included: com.squareup.okhttp3:okhttp-urlconnection:jar:3.11.0
[DEBUG]   Included: com.squareup.retrofit2:converter-jackson:jar:2.4.0
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-databind:jar:2.9.4
[DEBUG]   Included: com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.4
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0
[DEBUG]   Included: com.squareup.retrofit2:adapter-rxjava:jar:2.4.0
[DEBUG]   Included: com.microsoft.azure:azure-client-authentication:jar:1.6.0
[DEBUG]   Included: com.microsoft.azure:adal4j:jar:1.1.2
[DEBUG]   Included: com.nimbusds:oauth2-oidc-sdk:jar:4.5
[DEBUG]   Included: javax.mail:mail:jar:1.4.7
[DEBUG]   Included: javax.activation:activation:jar:1.1
[DEBUG]   Included: net.jcip:jcip-annotations:jar:1.0
[DEBUG]   Included: net.minidev:json-smart:jar:1.1.1
[DEBUG]   Included: com.nimbusds:lang-tag:jar:1.4
[DEBUG]   Included: com.nimbusds:nimbus-jose-jwt:jar:3.1.2
[DEBUG]   Included: org.bouncycastle:bcprov-jdk15on:jar:1.51
[DEBUG]   Included: com.microsoft.azure:azure-annotations:jar:1.2.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-resources:jar:1.14.0
[DEBUG]   Included: org.slf4j:slf4j-simple:jar:1.7.5
[DEBUG]   Included: io.reactivex:rxjava:jar:1.3.8
[DEBUG]   Included: org.apache.httpcomponents:httpcore:jar:4.4.5
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-storage:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-network:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-compute:jar:1.14.0
[DEBUG]   Included: com.google.code.gson:gson:jar:2.2.4
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-graph-rbac:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-keyvault:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-keyvault:jar:1.0.0
[DEBUG]   Included: com.microsoft.azure:azure-keyvault-webkey:jar:1.0.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-batch:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-trafficmanager:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-dns:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-redis:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-appservice:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-storage:jar:6.1.0
[DEBUG]   Included: com.microsoft.azure:azure-keyvault-core:jar:0.8.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-locks:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-eventhub:jar:1.14.0
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-core:jar:2.9.4
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-cdn:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-sql:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-containerinstance:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-containerregistry:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-containerservice:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-cosmosdb:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-search:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-msi:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-monitor:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-servicebus:jar:1.14.0
[DEBUG]   Included: joda-time:joda-time:jar:2.1
[DEBUG]   Included: com.microsoft.azure:azure-mgmt-batchai:jar:1.14.0
[DEBUG]   Included: com.microsoft.azure:applicationinsights-core:jar:1.0.9
[DEBUG]   Included: eu.infomas:annotation-detector:jar:3.0.4
[DEBUG]   Included: commons-io:commons-io:jar:2.4
[DEBUG]   Included: org.apache.commons:commons-lang3:jar:3.1
[DEBUG]   Included: org.apache.httpcomponents:httpclient:jar:4.5.3
[DEBUG]   Included: commons-logging:commons-logging:jar:1.2
[DEBUG]   Included: commons-codec:commons-codec:jar:1.9
[DEBUG]   Included: commons-net:commons-net:jar:3.6
[DEBUG]   Included: org.zeroturnaround:zt-zip:jar:1.13
[DEBUG]   Included: junit:junit:jar:4.12
[DEBUG]   Included: org.hamcrest:hamcrest-core:jar:1.3
[DEBUG] Configuring mojo com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy from plugin realm ClassRealm[plugin>com.microsoft.azure:azure-webapp-maven-plugin:1.4.0, parent: sun.misc.Launcher$AppClassLoader@1b6d3586]
[DEBUG] Configuring mojo 'com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy' with basic configurator -->
[DEBUG]   (f) allowTelemetry = true
[DEBUG]   (f) appName = freebergpetclinic
[DEBUG]   (f) buildDirectory = /usr/jason/clouddrive/e2e-java-experience-in-app-service-linux/initial-cloudshell/spring-framework-petclinic/target
[DEBUG]   (f) failsOnError = true
[DEBUG]   (f) javaWebContainer = tomcat 8.5
[DEBUG]   (f) linuxRuntime = tomcat 8.5-jre8
[DEBUG]   (f) path = /
[DEBUG]   (f) plugin = Component Descriptor: role: 'org.apache.maven.plugin.Mojo', implementation: 'com.microsoft.azure.maven.webapp.DeployMojo', role hint: 'com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy'
role: 'org.apache.maven.plugin.Mojo', implementation: 'com.microsoft.azure.maven.webapp.HelpMojo', role hint: 'com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:help'
---
[DEBUG]   (f) pricingTier = S1
[DEBUG]   (f) project = MavenProject: org.springframework.samples:spring-petclinic:5.0.8 @ /usr/jason/clouddrive/e2e-java-experience-in-app-service-linux/initial-cloudshell/spring-framework-petclinic/pom.xml
[DEBUG]   (f) region = westus
[DEBUG]   (f) resourceGroup = freebergDemo
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@464a4442
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@3bc735b3
[DEBUG]   (f) skip = false
[DEBUG]   (f) stopAppDuringDeployment = false
[DEBUG] -- end configuration --
AI: INFO 05-09-2018 19:47, 1: Configuration file has been successfully found as resource
AI: INFO 05-09-2018 19:47, 1: Configuration file has been successfully found as resource
[DEBUG] Failed to authenticate with Azure CLI 2.0
[DEBUG]
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at com.microsoft.azure.credentials.AzureCliCredentials.environment(AzureCliCredentials.java:118)
        at com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl.buildRestClient(AzureConfigurableImpl.java:129)
        at com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl.buildRestClient(AzureConfigurableImpl.java:141)
        at com.microsoft.azure.management.Azure$ConfigurableImpl.authenticate(Azure.java:256)
        at com.microsoft.azure.maven.auth.AzureAuthHelper.getAuthObjFromAzureCli(AzureAuthHelper.java:203)
        at com.microsoft.azure.maven.auth.AzureAuthHelper.getAuthObj(AzureAuthHelper.java:129)
        at com.microsoft.azure.maven.auth.AzureAuthHelper.getAzureClient(AzureAuthHelper.java:71)
        at com.microsoft.azure.maven.AbstractAzureMojo.getAzureClient(AbstractAzureMojo.java:205)
        at com.microsoft.azure.maven.webapp.AbstractWebAppMojo.getWebApp(AbstractWebAppMojo.java:264)
        at com.microsoft.azure.maven.webapp.DeployMojo.createOrUpdateWebApp(DeployMojo.java:52)
        at com.microsoft.azure.maven.webapp.DeployMojo.doExecute(DeployMojo.java:47)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:288)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.396 s
[INFO] Finished at: 2018-09-05T19:47:17+00:00
[INFO] Final Memory: 59M/282M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project spring-petclinic: Failed to authenticate with Azure. Please check your configuration. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project spring-petclinic: Failed to authenticate with Azure. Please check your configuration.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to authenticate with Azure. Please check your configuration.
        at com.microsoft.azure.maven.AbstractAzureMojo.handleException(AbstractAzureMojo.java:347)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:293)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.microsoft.azure.maven.auth.AzureAuthFailureException: Failed to authenticate with Azure. Please check your configuration.
        at com.microsoft.azure.maven.AbstractAzureMojo.getAzureClient(AbstractAzureMojo.java:208)
        at com.microsoft.azure.maven.webapp.AbstractWebAppMojo.getWebApp(AbstractWebAppMojo.java:264)
        at com.microsoft.azure.maven.webapp.DeployMojo.createOrUpdateWebApp(DeployMojo.java:52)
        at com.microsoft.azure.maven.webapp.DeployMojo.doExecute(DeployMojo.java:47)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:288)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### PR DESCRIPTION
**Pull request by jdneo**
-	Check if the user is in the Cloud Shell through `ACC_CLOUD`
-	If yes, use MSI to auth
-	If no, use Azure CLI to auth

Resolve #382 #358

### CODE REVIEW

File: azure-maven-plugin-lib/src/main/java/com/microsoft/azure/maven/auth/AzureAuthHelper.java [hunk 1]
```diff
@@ -38,10 +39,12 @@
     public static final String CERTIFICATE = "certificate";
     public static final String CERTIFICATE_PASSWORD = "certificatePassword";
     public static final String ENVIRONMENT = "environment";
+    public static final String CLOUD_SHELL_ENV_KEY = "ACC_CLOUD";
 
     public static final String AUTH_WITH_SERVER_ID = "Authenticate with ServerId: ";
     public static final String AUTH_WITH_FILE = "Authenticate with file: ";
     public static final String AUTH_WITH_AZURE_CLI = "Authenticate with Azure CLI 2.0";
+    public static final String AUTH_WITH_MSI = "Detected in the Azure Cloud Shell, using MSI to authenticate.";
```
Comment (andxu) [inline azure-maven-plugin-lib/src/main/java/com/microsoft/azure/maven/auth/AzureAuthHelper.java]: Remove 'Detected'

File: azure-maven-plugin-lib/src/main/java/com/microsoft/azure/maven/auth/AzureAuthHelper.java [hunk 2]
```diff
@@ -277,4 +288,8 @@ protected ApplicationTokenCredentials getAppTokenCredentialsFromServer(Server se
 
         return null;
     }
+
+    private boolean isInCloudShell() {
```
Comment (andxu) [inline azure-maven-plugin-lib/src/main/java/com/microsoft/azure/maven/auth/AzureAuthHelper.java]: static
