### PR TITLE
Fixes for webapp track2 migration

### LINKED ISSUE #1280: Pop up error when user skip the <runtime> configuration.
### Plugin name and version

Azure-webapp-maven-plugin:1.13.0-SNAPSHOT

### Actual behavior

image

### Steps to reproduce the problem

1.Skip the runtime configuration
2.Run mvn azure-webapp:deploy

### LINKED ISSUE #1283: The app service plan will be identified as resource group when user specify<appServicePlanResourceGroup>in configuration
### Plugin name and version

OS: Win/Mac
Plugin: Azure-webapp-maven-plugin:1.13.0-SNAPSHOT

### Actual behavior

image

### Steps to reproduce the problem
1.Specify appServicePlanResourceGroup in configuration
2.Run mvn azure-webapp:deploy

### Plugin configuration in your pom.xml

image

### PR DESCRIPTION
**Pull request by Flanker32**
- Skip deployment for docker
- Fix using wrong resource group when create app service plan, fixes #1283
- Enable user deploy without set app service runtime, fixes #1280
- Fix temp staging folder creation issue

### CODE REVIEW

File: azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/DeployMojo.java [hunk 1]
```diff
@@ -87,60 +92,68 @@ private IWebAppDeploymentSlot getDeploymentSlot(final WebAppConfig config) throw
...
-        Log.info(String.format(UPDATE_WEBAPP_DONE, webApp.entity().getName()));
+        Log.info(String.format(UPDATE_WEBAPP_DONE, webApp.name()));
         return result;
     }
 
+    // todo: Extract resource group logic to library
+    private ResourceGroup getOrCreateResourceGroup(final WebAppConfig webAppConfig) {
+        try {
+            return az.getAzureResourceManager().resourceGroups().getByName(webAppConfig.getResourceGroup());
+        } catch (Exception e) {
```
Comment (andxu) [inline azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/DeployMojo.java:133]: identify the right exception when resource group doesn't exist, don't catch all Exceptions since some times it is due to other errors like Network issue.

File: azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/DeployMojo.java [hunk 2]
```diff
@@ -211,7 +211,8 @@ private void deployArtifacts(IAppService target, WebAppConfig config) throws Azu
         // call correspond deploy method when deploy artifact only
         if (resources.size() == 1) {
             final Pair<File, DeployType> resource = resources.get(0);
-            target.deploy(resource.getRight(), resource.getLeft());
+            final DeployType deployType = target.getRuntime().getWebContainer() == WebContainer.JBOSS_72 ? DeployType.EAR : resource.getRight();
```
Comment (andxu) [inline azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/DeployMojo.java:219]: why we need to override deployType?

File: azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/DeployMojo.java [hunk 3]
```diff
@@ -59,6 +59,9 @@
     private static final String DEPLOY_START = "Trying to deploy artifact to %s...";
     private static final String DEPLOY_FINISH = "Successfully deployed the artifact to https://%s";
     private static final String SKIP_DEPLOYMENT_FOR_DOCKER_APP_SERVICE = "Skip deployment for docker app service";
+    private static final String NO_RUNTIME_CONFIG = "No runtime related configuration is specified in pom.xml. " +
```
Comment (andxu) [inline azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/DeployMojo.java:62]: No runtime related configuration is in pom.xml=>You need to specified runtime in pom.xml for creating azure webapps

File: azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/DeployMojo.java (hunk 2 above)
Comment (Flanker32) [reply azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/DeployMojo.java:219]: We will use file type as the deploy type by default, however, JBOSSEAP runtime both support `ear` and `war` artifact, but WarDeploy didn't support JBOSSEAP runtime(service will throw exception when target runtime is joss), so use EAR deploy for JBOSSEAP runtime

**Review by andxu — APPROVED** [review]
